site_name: 云计算技术

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
    #- navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.code.select

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary:  indigo

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/github
    - icon: fontawesome/brands/gitlab
    - icon: fontawesome/brands/x-twitter
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Copyright
copyright: Copyright &copy; 2025 - 2035 abbott

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# plugins:
#   - search
#   - awesome-pages


nav:
  - Linux系统管理:
    - 第一章 初识Linux系统: Linux系统管理/认识Linux系统/第一章Linux发展史/index.md
    - 第二章 Linux系统基本管理: Linux系统管理/Linux系统基本管理/index.md
    - 第三章 Linux文件系统: Linux系统管理/Linux文件系统/index.md
    - 第四章 Linux用户与权限管理: Linux系统管理/Linux用户与权限管理/index.md
    - 第五章 Linux进程管理: Linux系统管理/Linux进程管理/index.md
    - 第六章 Linux网络管理: Linux系统管理/Linux网络管理/index.md
    - 第七章 Linux存储管理: Linux系统管理/Linux存储管理/index.md
    - 第八章 Linux服务管理: Linux系统管理/Linux服务管理/index.md
    - 第九章 Linux日志管理: Linux系统管理/Linux日志管理/index.md
    - 第十章 Linux安全管理: Linux系统管理/Linux安全管理/index.md
    - 第十一章 Linux性能优化: Linux系统管理/Linux性能优化/index.md
    - 第十二章 Linux故障排除: Linux系统管理/Linux故障排除/index.md 

  - 数据库:
    - 数据库: 数据库/index.md
    - MySQL: 数据库/MySQL/index.md
    - PostgreSQL: 数据库/PostgreSQL/index.md
    - MongoDB: 数据库/MongoDB/index.md
    - Redis: 数据库/Redis/index.md  
  
  
  - Container:
    - 容器基本概念: Container/index.md
    - Docker: Container/Docker/index.md
    - Containerd: index.md
    - Podman: index.md
    - Kata Containers: index.md
    - rkt: index.md
    - LXC/LXD: index.md
    - Open Container Initiative (OCI): index.md
    - Container Networking: index.md
    - Container Storage: index.md
    - Container Security: index.md
    - Container Orchestration: index.md
    - Container Monitoring: index.md
    - Container Logging: index.md
    - Container Performance Tuning: index.md
    - Container Troubleshooting: index.md
  - Kubernetes:   
    - 第一章 概述: Kubernetes/kubernetes概述/index.md
    - 第二章 架构与组件: Kubernetes/Kubernetes架构与组件/index.md
    - 第三章 部署: Kubernetes/kubernetes部署/index.md
    - 第四章 组件: index.md
    - 第五章 Pod: Kubernetes/Pod/index.md
    - 第六章 控制器: Kubernetes/控制器/index.md
    - 第七章 网络控制: Kubernetes/网络控制/index.md
    - 第八章 存储: Kubernetes/存储/index.md
    - 第九章 配置: Kubernetes/配置/index.md
    - 第十章 安全: Kubernetes/安全/index.md
    - 第十一章 调度、抢占: Kubernetes/调度与抢占/index.md
    - 第十二章 监控与日志: Kubernetes/监控与日志/index.md
    - 第十三章 升级与回滚: Kubernetes/升级与回滚/index.md
    - 第十四章 集群管理: Kubernetes/集群管理/index.md
    - 第十五章 资源管理: Kubernetes/资源管理/index.md
    - 第十六章 服务发现与负载均衡: Kubernetes/服务发现与负载均衡/index.md
    - 第十七章 Helm: Kubernetes/Helm/index.md
    - 第十八章 Operator: Kubernetes/Operator/index.md 
  - OpenShift:
    - 第一章 OpenShift概述: OpenShift/OpenShift概述/index.md
    - 第二章 OpenShift架构: OpenShift/OpenShift架构/index.md
    - 第三章 OpenShift安装: OpenShift/OpenShift安装/index.md
    - 第四章 OpenShift项目管理: OpenShift/OpenShift项目管理/index.md
    - 第五章 OpenShift应用管理: OpenShift/OpenShift应用管理/index.md
    - 第六章 OpenShift网络管理: OpenShift/OpenShift网络管理/index.md
    - 第七章 OpenShift存储管理: OpenShift/OpenShift存储管理/index.md
    - 第八章 OpenShift安全管理: OpenShift/OpenShift安全管理/index.md
    - 第九章 OpenShift监控与日志: OpenShift/OpenShift监控与日志/index.md
    - 第十章 OpenShift升级与回滚: OpenShift/OpenShift升级与回滚/index.md
    - 第十一章 OpenShift集群管理: OpenShift/OpenShift集群管理/index.md
    - 第十二章 OpenShift资源管理: OpenShift/OpenShift资源管理/index.md
    - 第十三章 OpenShift服务发现与负载均衡: OpenShift/OpenShift服务发现与负载均衡/index.md
    - 第十四章 OpenShift CI/CD: OpenShift/OpenShift CI-CD/index.md
    - 第十五章 OpenShift Operator: OpenShift/OpenShift Operator/index.md
    - 第十六章 OpenShift多集群管理: OpenShift/OpenShift多集群管理/index.md
    - 第十七章 OpenShift性能优化: OpenShift/OpenShift性能优化/index.md
    - 第十八章 OpenShift故障排除: OpenShift/OpenShift故障排除/index.md
    - 第十九章 OpenShift社区与资源: OpenShift/OpenShift社区与资源/index.md
  - Ansible:
    - 第一章 Ansible概述: Ansible/Ansible概述/index.md
    - 第二章 Ansible安装与配置: Ansible/Ansible安装与配置/index.md
    - 第三章 Ansible基础: Ansible/Ansible基础/index.md
    - 第四章 Ansible Playbook: Ansible/Ansible Playbook/index.md
    - 第五章 Ansible角色: Ansible/Ansible角色/index.md
    - 第六章 Ansible模块: Ansible/Ansible模块/index.md
    - 第七章 Ansible变量与模板: Ansible/Ansible变量与模板/index.md
    - 第八章 Ansible循环与条件: Ansible/Ansible循环与条件/index.md
    - 第九章 Ansible错误处理: Ansible/Ansible错误处理/index.md
    - 第十章 Ansible高级功能: Ansible/Ansible高级功能/index.md
    - 第十一章 Ansible性能优化: Ansible/Ansible性能优化/index.md
    - 第十二章 Ansible故障排除: Ansible/Ansible故障排除/index.md
    - 第十三章 Ansible实战案例: Ansible/Ansible实战案例/index.md
    - 第十四章 Ansible社区资源: Ansible/Ansible社区资源/index.md

  - OpenStack: 
    - 第一章 理解云计算: OpenStack/index.md
    - 第二章 OpenStack概述: OpenStack/OpenStack概述/index.md
    - 第三章 OpenStack架构: OpenStack/OpenStack架构/index.md 
    - 第四章 OpenStack安装: OpenStack/OpenStack安装/index.md
    - 第五章 OpenStack计算服务: OpenStack/OpenStack计算服务/index.md
    - 第六章 OpenStack存储服务: OpenStack/OpenStack存储服务/index.md
    - 第七章 OpenStack网络服务: OpenStack/OpenStack网络服务/index.md  
    - 第八章 OpenStack身份服务: OpenStack/OpenStack身份服务/index.md
    - 第九章 OpenStack镜像服务: OpenStack/OpenStack镜像服务/index
    - 第十章 OpenStack监控与日志: OpenStack/OpenStack监控与日志/index.md
    - 第十一章 OpenStack安全: OpenStack/OpenStack安全/index.md
    - 第十二章 OpenStack性能优化: OpenStack/OpenStack性能优化/index.md
    - 第十三章 OpenStack故障排除: OpenStack/OpenStack故障排除/index.md
    - 第十四章 OpenStack实战案例: OpenStack/OpenStack实战案例/index.md
    - 第十五章 OpenStack社区资源: OpenStack/OpenStack社区资源/index.md

  - Ceph分布式存储:
    - 第一章 理解分布式: Ceph分布式存储/什么是分布式存储/index.md
    - 第二章 Ceph概述: Ceph分布式存储/Ceph简介/index.md
  - DevOps: index.md
  - AIOps: index.md
  - Python: index.md
  - Golang: 
    - 基础部分: 编程语言/golang/Golang基础语法/index.md
    - 进阶部分: 编程语言/golang/进阶部分/index.md
    - 并发编程: 编程语言/golang/并发编程/index.md
    - 网络编程: 编程语言/golang/网络编程与Web开发/index.md
    - 项目实战: index.md
  - ShellScritpt: 
    - 第一章节 入门: 编程语言/ShellScript/入门/index.md
    - 第二章节 运算符: 编程语言/ShellScript/运算符/index.md
    - 第三章节 字符串和数组: 编程语言/ShellScript/字符串和数组/index.md
    - 第四章节 流程控制: 编程语言/ShellScript/流程控制/index.md
    - 第五章节 函数: 编程语言/ShellScript/函数/index.md
    - 进阶部分: index.md
    - 项目实战: index.md



 
  - 监控系统:
    - zabbix: 监控系统/Zabbix/index.md 
    - Prometheus: 监控系统/Prometheus/index.md
    - Grafana: 监控系统/Grafana/index.md
    - Loki: 监控系统/Loki/index.md
    - ELK: 监控系统/ELK/index.md
  




